name: Evaluate test cases

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev

env:
  DEV_PROJECT_ID: propane-will-468518-d0

jobs:
  generate-testcases:
    runs-on: ubuntu-latest
    steps:
      - name: Calculate GCP project ID
        id: calculate_project_id
        run: |
          if [ "${{ github.event.inputs.environment }}" = "prod" ]; then
            echo "project_id=some-prod-project-id" >> $GITHUB_OUTPUT
          else
            echo "project_id=${{ env.DEV_PROJECT_ID }}" >> $GITHUB_OUTPUT
          fi
      - name: Checkout repository
        uses: actions/checkout@v5.0.0

      - name: Set up Python 3.12
        uses: actions/setup-python@v6.0.0
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v6.8.0

      - name: Install dependencies
        run: |
          uv sync

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
          project_id: ${{ steps.calculate_project_id.outputs.project_id }}

      - name: Evaluate test cases
        run: |
          uv run -- python -m evaluation.evaluate -k -u
